web/password_manager/database/models.py
from .. import db


class users(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(100))
    email = db.Column(db.String(100))
    password = db.Column(db.String(250))
    master_password = db.Column(db.String(250))

    def __init__(self, username, email, password, master_password):
        self.username = username
        self.email = email
        self.password = password
        self.master_password = master_password


class passwords(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(100))
    service_name = db.Column(db.String(250))
    password = db.Column(db.String(250))

    def __init__(self, username, service_name, password):
        self.username = username
        self.service_name = service_name
        self.password = password


class attempts(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(100))
    ip_address = db.Column(db.String(100))
    time = db.Column(db.String(100))

    def __init__(self, username, ip_address, time):
        self.username = username
        self.ip_address = ip_address
        self.time = time


class resets(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(100))
    reset_id = db.Column(db.String(250))
    end_time = db.Column(db.String(100))

    def __init__(self, email, reset_id, end_time):
        self.email = email
        self.reset_id = reset_id
        self.end_time = end_time


class passwords_history(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(100))
    service_name = db.Column(db.String(250))
    password = db.Column(db.String(250))
    time = db.Column(db.String(100))

    def __init__(self, username, service_name, password, time):
        self.username = username
        self.service_name = service_name
        self.password = password
        self.time = time


class services_info(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(100))
    service_name = db.Column(db.String(250))
    user_name = db.Column(db.String(100))
    service_url = db.Column(db.String(250))
    image_url = db.Column(db.String(250))

    def __init__(self, username, service_name, user_name, service_url, image_url):
        self.username = username
        self.service_name = service_name
        self.user_name = user_name
        self.service_url = service_url
        self.image_url = image_url

web/password_manager/__init__.py
from flask import Flask
from extensions import *


def create_app():
    app = Flask(__name__, instance_relative_config=False)
    app.config.from_object("config.DevelopmentConfig")

    db.init_app(app)
    limiter.init_app(app)

    with app.app_context():
        from .auth.routes import auth
        app.register_blueprint(auth, url_prefix="/api/auth")

        from .passwords.routes import passwords
        app.register_blueprint(passwords, url_prefix="/api/passwords")

        from .website.routes import website
        app.register_blueprint(website)

        db.create_all()

        return app

web/password_manager/website/routes.py
from flask import Blueprint, render_template, session, flash, redirect, url_for
from ..database.manager import AuthDbManager
from .. import limiter

website = Blueprint('website', __name__)


@website.route('/', methods=['GET'])
def home():
    return render_template("home.html")


@website.route('/register', methods=['GET'])
def register():
    return render_template("auth/register.html")


@website.route('/login', methods=['GET'])
def login():
    return render_template("auth/login.html")


@ website.route('/reset', methods=['GET'])
@ limiter.exempt
def reset():
    return render_template("auth/reset.html")


@website.route('/reset/<reset_id>', methods=['GET'])
def reset_with_token(reset_id):
    db = AuthDbManager()
    if db.is_allowed_for_resetting(reset_id) and db.is_reset_link_valid(reset_id):
        session["reset_id"] = reset_id
        return render_template("auth/reset_with_token.html")
    else:
        return "", 401


@ website.route('/dashboard', methods=['GET'])
@ limiter.exempt
def dashboard():
    if not session.get("username"):
        flash("Ta akcja wymaga zalogowania!")
        return redirect(url_for('website.login'))
    return render_template('passwords/dashboard.html')


@ website.route('/dashboard_more', methods=['GET'])
@ limiter.exempt
def dashboard_more():
    if not session.get("username"):
        flash("Ta akcja wymaga zalogowania!")
        return redirect(url_for('website.login'))
    return render_template('passwords/dashboard_more.html')


@ website.route('/logout', methods=['GET'])
@ limiter.exempt
def logout():
    session.clear()
    return redirect(url_for('website.home'))

web/password_manager/templates/base.html
<html>

<head>
    <link rel="stylesheet" href="../static/css/base.css" />
    <meta charset="utf-8">
    <title>Password Manager</title>
</head>

<body>
    <header>
        <img src="{{ url_for('static', filename='/images/logo.svg') }}" width = 50/>
        <nav>
            {% if not session['username'] %}
            <li id="home_tab"><a href="{{ url_for('website.home') }}">Strona Główna</a></li>
            <li id="login_tab"><a href="{{ url_for('website.login') }}">Zaloguj się</a></li>
            <li id="signup_tab"><a href="{{ url_for('website.register') }}">Zarejestruj się</a></li>
            <li id="reset_tab"><a href="{{ url_for('website.reset') }}">Zresetuj Hasło</a></li>
            {% endif %} {% if session['username'] %}
            <li id="dashboard_tab"><a href="{{ url_for('website.dashboard') }}">Moje Konto</a></li>
            <li id="info_tab"><a href="{{ url_for('website.dashboard_more') }}">Twoje Informacje w Serwisach</a></li>
            <li id="logout_tab"><a href="{{ url_for('website.logout') }}">Wyloguj się</a></li>
            {% endif %}
            </ul>
        </nav>
    </header>

    <div id="flash">
        {% with messages = get_flashed_messages() %} {% if messages %}
        <ul class="flash_messages">
            {% for message in messages %}
            <li>
                <h3> {{ message }} </h3>
            </li>
            {% endfor %}
        </ul>
        {% endif %} {% endwith %}
    </div>


    <div id="container">
        {% block content %}{% endblock %}
    </div>

</body>

<footer>
    <div>Icons made by <a href="https://www.flaticon.com/authors/freepik" title="Freepik">Freepik</a> from <a
            href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a></div>
</footer>

</html>

web/password_manager/templates/home.html
{% extends "base.html" %} {% block content %}

<head>
    <link rel="stylesheet" href="../static/css/home.css" />
</head>

<body>
    <main>
        <p>,,Najczęściej używany przeze mnie menadżer haseł."</p>
        <p>,,Bardzo dobry poziom usług."</p>
        <p>,,Mój ulubiony menadżer haseł."</p>
    </main>

</body>

{% endblock %}